import { Destination } from './store';

export const regions = [
  'Littoral',
  'Centre',
  'South',
  'East',
  'North',
  'Adamawa',
  'Far North',
  'Northwest',
  'Southwest',
  'West',
];

export const categories = [
  'Beaches',
  'Mountains',
  'Waterfalls',
  'National Parks',
  'Cultural Sites',
  'Historical Sites',
  'Wildlife',
  'Adventure',
];

export const mockDestinations: Destination[] = [
  {
    id: '1',
    name: 'Mount Cameroon',
    region: 'Southwest',
    category: 'Mountains',
    description:
      'Mount Cameroon is an active volcano in the South West region of Cameroon, near the Gulf of Guinea. It is the highest peak in sub-Saharan western and central Africa, the fourth-most prominent peak in Africa, and the 31st-most prominent peak in the world.',
    images: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200',
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200',
      'https://images.unsplash.com/photo-1454496522488-7a8e488e8606?w=1200',
    ],
    coordinates: { lat: 4.2034, lng: 9.1706 },
    entryFee: 5000,
    difficulty: 'Hard',
    rating: 4.8,
    reviews: 245,
    activities: ['Hiking', 'Camping', 'Photography', 'Wildlife Watching'],
    openingHours: 'Open 24/7',
    nearbyAttractions: ['Limbe Beach', 'Botanical Gardens'],
    howToGetThere: {
      byCar: 'Drive from Douala via the N3 highway, approximately 2 hours',
      byBus: 'Take a bus from Douala to Buea, then arrange local transport',
      distance: '75km from Douala',
    },
  },
  {
    id: '2',
    name: 'Limbe Beach',
    region: 'Southwest',
    category: 'Beaches',
    description:
      'Limbe Beach is a stunning black sand beach located in the coastal town of Limbe. Known for its unique volcanic sand and beautiful ocean views, it offers a perfect blend of relaxation and scenic beauty.',
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200',
      'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200',
      'https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=1200',
    ],
    coordinates: { lat: 4.0167, lng: 9.2 },
    entryFee: 0,
    difficulty: 'Easy',
    rating: 4.6,
    reviews: 312,
    activities: ['Swimming', 'Sunbathing', 'Beach Sports', 'Seafood Dining'],
    openingHours: 'Open 24/7',
    nearbyAttractions: ['Limbe Wildlife Centre', 'Botanical Gardens'],
    howToGetThere: {
      byCar: 'Drive from Douala via the N3, approximately 1.5 hours',
      byBus: 'Regular buses from Douala to Limbe',
      distance: '60km from Douala',
    },
  },
  {
    id: '3',
    name: 'Waza National Park',
    region: 'Far North',
    category: 'National Parks',
    description:
      'Waza National Park is Cameroon\'s most famous wildlife reserve. It offers incredible opportunities to see elephants, lions, giraffes, and many other African animals in their natural habitat.',
    images: [
      'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200',
      'https://images.unsplash.com/photo-1549366021-9f761d450615?w=1200',
      'https://images.unsplash.com/photo-1535338454770-6c4f4ff7b1f1?w=1200',
    ],
    coordinates: { lat: 11.4, lng: 14.7 },
    entryFee: 15000,
    difficulty: 'Medium',
    rating: 4.9,
    reviews: 189,
    activities: ['Safari', 'Wildlife Photography', 'Bird Watching', 'Guided Tours'],
    openingHours: '6:00 AM - 6:00 PM',
    nearbyAttractions: ['Maroua Market', 'Rhumsiki Peak'],
    howToGetThere: {
      byCar: 'Drive from Maroua, approximately 2 hours',
      byBus: 'Bus to Waza village, then park entrance',
      distance: '120km from Maroua',
    },
  },
  {
    id: '4',
    name: 'Ekom-Nkam Waterfalls',
    region: 'Littoral',
    category: 'Waterfalls',
    description:
      'Ekom-Nkam is a spectacular waterfall that drops approximately 80 meters. Featured in the Tarzan movies, this breathtaking natural wonder is surrounded by lush rainforest.',
    images: [
      'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=1200',
      'https://images.unsplash.com/photo-1508668191897-d2a39c87fc86?w=1200',
      'https://images.unsplash.com/photo-1484406566174-9da000fda645?w=1200',
    ],
    coordinates: { lat: 4.8167, lng: 10.4667 },
    entryFee: 2000,
    difficulty: 'Medium',
    rating: 4.7,
    reviews: 156,
    activities: ['Hiking', 'Photography', 'Swimming', 'Nature Walks'],
    openingHours: '7:00 AM - 6:00 PM',
    nearbyAttractions: ['Mami Wata Waterfalls', 'Local Villages'],
    howToGetThere: {
      byCar: 'From Douala, drive towards Nkongsamba, then to Melong',
      byBus: 'Bus to Melong, then motorcycle taxi',
      distance: '130km from Douala',
    },
  },
  {
    id: '5',
    name: 'Rhumsiki Peak',
    region: 'Far North',
    category: 'Mountains',
    description:
      'Rhumsiki is a unique landscape of volcanic plugs and stunning rock formations. The village at the base offers cultural experiences and panoramic views of the Mandara Mountains.',
    images: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200',
      'https://images.unsplash.com/photo-1519904981063-b0cf448d479e?w=1200',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200',
    ],
    coordinates: { lat: 10.6667, lng: 13.7667 },
    entryFee: 3000,
    difficulty: 'Medium',
    rating: 4.8,
    reviews: 98,
    activities: ['Hiking', 'Cultural Tours', 'Photography', 'Rock Climbing'],
    openingHours: 'Open 24/7',
    nearbyAttractions: ['Maroua', 'Traditional Villages'],
    howToGetThere: {
      byCar: 'Drive from Maroua, approximately 1.5 hours',
      byBus: 'Bus or shared taxi from Maroua',
      distance: '55km from Maroua',
    },
  },
  {
    id: '6',
    name: 'Kribi Beach',
    region: 'South',
    category: 'Beaches',
    description:
      'Kribi is home to some of Cameroon\'s most beautiful white sand beaches. The coastal town offers excellent seafood, water sports, and the famous Lobe Waterfalls that flow directly into the ocean.',
    images: [
      'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200',
      'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=1200',
      'https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=1200',
    ],
    coordinates: { lat: 2.95, lng: 9.9167 },
    entryFee: 0,
    difficulty: 'Easy',
    rating: 4.7,
    reviews: 278,
    activities: ['Swimming', 'Fishing', 'Boat Tours', 'Beach Volleyball'],
    openingHours: 'Open 24/7',
    nearbyAttractions: ['Lobe Waterfalls', 'Chutes de la Lobe'],
    howToGetThere: {
      byCar: 'Drive from Douala, approximately 3 hours',
      byBus: 'Regular buses from Douala and Yaoundé',
      distance: '150km from Douala',
    },
  },
  {
    id: '7',
    name: 'Dja Faunal Reserve',
    region: 'East',
    category: 'National Parks',
    description:
      'A UNESCO World Heritage Site, Dja Faunal Reserve is one of the largest and best-protected rainforests in Africa. It\'s home to numerous endangered species including lowland gorillas and forest elephants.',
    images: [
      'https://images.unsplash.com/photo-1535338454770-6c4f4ff7b1f1?w=1200',
      'https://images.unsplash.com/photo-1564760055775-d63b17a55c44?w=1200',
      'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200',
    ],
    coordinates: { lat: 3.0, lng: 13.0 },
    entryFee: 20000,
    difficulty: 'Hard',
    rating: 4.9,
    reviews: 67,
    activities: ['Guided Jungle Tours', 'Wildlife Watching', 'Bird Watching', 'Photography'],
    openingHours: '6:00 AM - 5:00 PM',
    nearbyAttractions: ['Sangmelima', 'Local Pygmy Communities'],
    howToGetThere: {
      byCar: 'From Yaoundé, drive towards Sangmelima',
      byBus: 'Bus to Sangmelima, then arrange park transport',
      distance: '200km from Yaoundé',
    },
  },
  {
    id: '8',
    name: 'Foumban Royal Palace',
    region: 'West',
    category: 'Cultural Sites',
    description:
      'The Royal Palace of Foumban is the home of the Sultan of Bamoun. This architectural masterpiece showcases the rich cultural heritage of the Bamoun people and houses an impressive museum.',
    images: [
      'https://images.unsplash.com/photo-1580407196238-dac33f57c410?w=1200',
      'https://images.unsplash.com/photo-1551632811-561732d1e306?w=1200',
      'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1200',
    ],
    coordinates: { lat: 5.7333, lng: 10.9 },
    entryFee: 5000,
    difficulty: 'Easy',
    rating: 4.6,
    reviews: 134,
    activities: ['Cultural Tours', 'Museum Visit', 'Photography', 'Art Shopping'],
    openingHours: '8:00 AM - 5:00 PM',
    nearbyAttractions: ['Foumban Artisan Market', 'Traditional Craft Centers'],
    howToGetThere: {
      byCar: 'Drive from Bafoussam, approximately 1 hour',
      byBus: 'Regular buses from Yaoundé or Bafoussam',
      distance: '70km from Bafoussam',
    },
  },
];

export const blogArticles = [
  {
    id: '1',
    title: '10 Must-Visit Hidden Gems in Cameroon',
    excerpt: 'Discover the lesser-known treasures of Cameroon that will take your breath away.',
    category: 'culture',
    image: 'https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=800',
    author: 'Sarah Johnson',
    date: '2025-11-15',
    readTime: '8 min read',
    content: `Cameroon is a country of incredible diversity, often called "Africa in miniature" for good reason. While many tourists flock to the popular destinations, there are countless hidden gems waiting to be discovered...`,
  },
  {
    id: '2',
    title: 'Essential Safety Tips for Traveling in Cameroon',
    excerpt: 'Stay safe while exploring the beauty of Cameroon with these practical tips.',
    category: 'safety',
    image: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800',
    author: 'Michael Chen',
    date: '2025-11-10',
    readTime: '6 min read',
    content: `Safety is paramount when traveling to any destination. Cameroon is generally safe for tourists who take sensible precautions...`,
  },
  {
    id: '3',
    title: 'Best Time to Visit Cameroon: A Seasonal Guide',
    excerpt: 'Plan your trip perfectly with our comprehensive guide to Cameroon\'s weather patterns.',
    category: 'weather',
    image: 'https://images.unsplash.com/photo-1601134467661-3d775b999c8b?w=800',
    author: 'Emma Thompson',
    date: '2025-11-05',
    readTime: '7 min read',
    content: `The climate in Cameroon varies significantly across regions. Understanding the weather patterns can help you plan the perfect trip...`,
  },
];
